# To run: conda env create -f environment.yml
name: nerf_maml
channels:
    - conda-forge
dependencies:
    - tensorflow-gpu
    - tensorboard
    - numpy
    - matplotlib
    - imageio
    - imageio-ffmpeg
    - configargparse
    # - imagemagick
